---
# The repository to use. Options: pbs-no-subscription, pbs-enterprise
pbs_repository_line: "deb [signed-by=/usr/share/keyrings/release-{{ ansible_distribution_release }}.gpg] http://download.proxmox.com/debian/pbs-client {{ ansible_distribution_release }} pbs-client-no-subscription"

# Proxmox GPG Key
pbs_gpg_key_url: "https://enterprise.proxmox.com/debian/proxmox-release-trixe.gpg"
pbs_gpg_key_dest: "/usr/share/keyrings/proxmox-archive-keyring.gpg"

proxmox_backup_password: "REPLACEME"
pbs_server_netbird: "backup.jitonline.local"
pbs_server_local: "backup.home"

backup_cron_command: "/root/backup.sh"
backup_cron_job_name: "Run Backup randomly once a day"

proxmox_arm_client: "https://github.com/wofferl/proxmox-backup-arm64/releases/download/4.1.2-1/proxmox-backup-client-static_4.1.2-1_arm64.deb"
