---
- name: Ensure dependencies are installed (Debian/Ubuntu)
  apt:
    name: [apt-transport-https, ca-certificates, curl, gnupg]
    state: present
    update_cache: yes
  when: ansible_os_family == 'Debian'

- name: Ensure dependencies are installed (Alpine)
  community.general.apk:
    name: [ca-certificates, curl]
    state: present
    update_cache: yes
  when: ansible_os_family == 'Alpine'

- name: Add NetBird GPG key (Debian)
  get_url:
    url: https://pkgs.netbird.io/debian/public.key
    dest: /usr/share/keyrings/netbird.asc
    mode: '0644'
  when: ansible_os_family == 'Debian'

- name: Add NetBird repository (Debian)
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/netbird.asc] https://pkgs.netbird.io/debian stable main"
    state: present
    filename: netbird
  when: ansible_os_family == 'Debian'

- name: Install NetBird (Debian)
  apt:
    name: netbird
    update_cache: yes
    state: present
  when: ansible_os_family == 'Debian'

- name: Install NetBird (Alpine)
  ansible.builtin.shell:
    cmd: "curl -fsSL https://pkgs.netbird.io/install.sh | sh"
    creates: /usr/bin/netbird
  when: ansible_os_family == 'Alpine'

- name: Check if NetBird is already connected
  command: netbird status
  register: netbird_status
  failed_when: false
  changed_when: false

- name: Bring NetBird up
  command: >
    netbird up 
    --management-url {{ netbird_management_url }} 
    --setup-key {{ netbird_setup_key }}
  when: "'Connected' not in netbird_status.stdout"
  # This prevents the setup key from being logged in plain text
  no_log: true

- name: Ensure Netbird is started (Alpine)
  ansible.builtin.service:
    name: netbird
    state: started
    enabled: yes
  when: ansible_os_family == 'Alpine'
  become: yes

- name: Populate service facts
  service_facts:

- name: Configure systemd-resolved
  block:
    - name: Check NetBird status for IP
      shell: "netbird status | grep 'NetBird IP' | awk '{print $3}' | cut -d/ -f1"
      register: netbird_ip
      failed_when: false
      changed_when: false

    - name: Configure DNS in resolved.conf
      lineinfile:
        path: /etc/systemd/resolved.conf
        regexp: '^#?DNS='
        line: "DNS={{ netbird_ip.stdout }}"
      when: netbird_ip.stdout | length > 0
      notify: Restart systemd-resolved

    - name: Configure Search Domains in resolved.conf
      lineinfile:
        path: /etc/systemd/resolved.conf
        regexp: '^#?Domains='
        line: "Domains=jitonline.local home"
      notify: Restart systemd-resolved

  # This block only runs if the service is present and active
  when: 
    - "'systemd-resolved.service' in services"
    - "services['systemd-resolved.service'].state == 'running'"

- name: Report service status
  debug:
    msg: "systemd-resolved is not running or not installed. Skipping configuration."
  when: >
    'systemd-resolved.service' not in services or 
    services['systemd-resolved.service'].state != 'running'
