---
- name: Ensure rsyslog package is installed
  ansible.builtin.package:
    name: rsyslog
    state: present
  become: yes

- name: Initialize syslog_host as null
  ansible.builtin.set_fact:
    syslog_host: null

- name: Try to ping Syslog candidates
  ansible.builtin.command: "ping -c 1 {{ item }}"
  register: ping_result
  ignore_errors: true
  changed_when: false
  loop: "{{ syslog_check_list }}"
  when: syslog_host is none

- name: Set syslog_host based on successful ping
  ansible.builtin.set_fact:
    syslog_host: "{{ item.item }}"
  loop: "{{ ping_result.results }}"
  when:
    - syslog_host is none
    - item.rc is defined
    - item.rc == 0
  no_log: true

- name: Fallback to default IP if no host responded
  ansible.builtin.set_fact:
    syslog_host: "{{ syslog_fallback_ip }}"
  when: syslog_host is none

- name: Ensure rsyslog.d directory exists
  ansible.builtin.file:
    path: /etc/rsyslog.d
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: yes

- name: Configure rsyslog
  ansible.builtin.template:
    src: remote.conf.j2
    dest: /etc/rsyslog.d/10-remote.conf
    owner: root
    group: root
    mode: '0644'
  become: yes
  notify: Restart rsyslog

- name: Ensure rsyslog service is running and enabled
  ansible.builtin.service:
    name: rsyslog
    state: started
    enabled: true
  become: yes

- name: Ensure rsyslog.conf includes rsyslog.d directory
  ansible.builtin.lineinfile:
    path: /etc/rsyslog.conf
    line: '$IncludeConfig /etc/rsyslog.d/*.conf'
    insertbefore: BOF
    state: present
  become: yes
  notify: Restart rsyslog

- name: Stop and disable default syslogd (Alpine)
  ansible.builtin.service:
    name: syslog
    state: stopped
    enabled: false
  become: yes
  when: ansible_os_family == 'Alpine'
  failed_when: false # Busybox syslog might not be running or present as a service name in all variants
