---
- name: set up host alias
  ansible.builtin.blockinfile:
    block: |
       10.5.69.8   ca.home
       10.5.69.51  logs.home
       10.5.69.5   zabbix.home
       10.5.69.24  semaphore.home
       10.5.69.11  backup.home
    dest: /etc/hosts
    state: present
