---
- name: Restart rsyslog
  ansible.builtin.service:
    name: rsyslog
    state: restarted

- name: Update CA trust store
  ansible.builtin.command: "{{ update_ca_cmd }}"
  listen: "update ca trust"
  vars:
    update_ca_cmd: >-
      {% if ansible_os_family == 'RedHat' %}update-ca-trust extract
      {% else %}update-ca-certificates
      {% endif %}
